window.revelar = ScrollReveal({reset:true});


revelar.reveal('.caixa', {
    duration: 1100,
    distance: '10px'
});


//DESENVOLVAM UMA APLICAÇÃO WEB RESPONSIVA PARA A DOMFIT

//UMA ACADEMIA RECÉM CRIADA E QUE NÃO POSSUI NENHUMA PLATAFORMA PARA EXIBIR SEUS PLANOS E SEUS PRODUTOS

//ELES NECESSITAM QUE O MAPA DA ACADEMIA ESTEJA DESCRITO NO SITE, ALÉM DE UMA PÁGINA ENGAJADA
